### ISSUE TITLE
ream-js

### ISSUE THREAD

**Issue by kozo002** [kozo002/nebura#3]
- もしかしてelectronでも使えるかも => ためしてみる
- iOS, Androidでも使えるのでnedbより有望株

**Comment by kozo002** [comment]
- `npm install --save realm` してみた
- このサンプルコードを electron で実行してみた https://realm.io/docs/react-native/latest/#installation
- エラーした

```
electron .
App threw an error during load
Error: Could not locate the bindings file. Tried:
 → /Users/kozo/tmp/nebura/node_modules/realm/build/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/build/Debug/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/build/Release/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/out/Debug/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/Debug/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/out/Release/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/Release/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/build/default/realm.node
 → /Users/kozo/tmp/nebura/node_modules/realm/compiled/6.1.0/darwin/x64/realm.node
    at bindings (/Users/kozo/tmp/nebura/node_modules/realm/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/kozo/tmp/nebura/node_modules/realm/lib/index.js:35:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    a
```

**Comment by kozo002** [comment]
electronで使いたい人はいるみたい
https://github.com/realm/realm-js/issues/262
